package fixes

import (
	"bytes"
	"fmt"

	"github.com/sailpoint-oss/barrelman"
	"github.com/sailpoint-oss/barrelman/codemod"
	ts "github.com/tree-sitter/go-tree-sitter"
)

// problemDetailsSchemaBody is the canonical RFC 7807 schema with
// SailPoint's required correlationId extension. Indented here with
// two-space base; callers re-indent to match their insertion point.
const problemDetailsSchemaBody = `ProblemDetails:
  type: object
  description: RFC 7807 Problem Details with SailPoint correlationId.
  required:
    - type
    - title
    - status
    - detail
    - instance
    - correlationId
  properties:
    type:
      type: string
      format: uri
      description: A URI reference identifying the problem type.
    title:
      type: string
      description: Short human-readable summary of the problem type.
    status:
      type: integer
      format: int32
      description: HTTP status code generated by the origin server.
    detail:
      type: string
      description: Human-readable explanation specific to this occurrence.
    instance:
      type: string
      format: uri-reference
      description: URI reference identifying the specific occurrence.
    correlationId:
      type: string
      format: uuid
      description: Unique identifier correlating this response to a server-side trace.`

// ErrorProblemDetailsMediaType implements the Fix for
// sailpoint-error-problem-details-media-type: adds
// `application/problem+json:` under the response's `content:` mapping
// (creating the content key if absent).
func ErrorProblemDetailsMediaType(ctx *codemod.FixContext, diag barrelman.Diagnostic) ([]codemod.Patch, error) {
	response := mappingForDiagnostic(ctx, diag)
	if response == nil {
		return nil, nil
	}
	// Locate or synthesize the content mapping.
	contentVal := codemod.MappingValueNode(response, ctx.Source, "content")
	if contentVal == nil {
		// Insert a fresh `content:` key containing application/problem+json.
		childIndent := codemod.ChildIndent(response, ctx.Source)
		inner := childIndent + 2
		pad := bytes.Repeat([]byte(" "), inner)
		value := fmt.Sprintf("\n%sapplication/problem+json:\n%s  schema:\n%s    $ref: '#/components/schemas/ProblemDetails'",
			pad, pad, pad)
		patch := codemod.InsertMappingPair(response, ctx.Source, "content", value)
		patch.URI = ctx.URI
		patch.RuleID = diag.Code
		patch.Description = "insert content with application/problem+json media type"
		return []codemod.Patch{patch}, nil
	}
	// content: exists - ensure application/problem+json is inside.
	contentMap := codemod.EnclosingBlockMapping(contentVal)
	if contentMap == nil {
		return nil, nil
	}
	if codemod.MappingHasKey(contentMap, ctx.Source, "application/problem+json") {
		return nil, nil
	}
	childIndent := codemod.ChildIndent(contentMap, ctx.Source)
	inner := childIndent + 2
	pad := bytes.Repeat([]byte(" "), inner)
	value := fmt.Sprintf("\n%sschema:\n%s  $ref: '#/components/schemas/ProblemDetails'", pad, pad)
	patch := codemod.InsertMappingPair(contentMap, ctx.Source, "application/problem+json", value)
	patch.URI = ctx.URI
	patch.RuleID = diag.Code
	patch.Description = "insert application/problem+json media type"
	return []codemod.Patch{patch}, nil
}

// ErrorProblemDetailsSharedComponent implements the Fix for
// sailpoint-error-problem-details-shared-component: when
// components.schemas.ProblemDetails is missing, appends the canonical
// schema under the schemas mapping. When responses reference the
// schema inline instead of via $ref, this fix does NOT rewrite the
// response (that falls into the "value mutation" bucket excluded from
// Phase 2).
func ErrorProblemDetailsSharedComponent(ctx *codemod.FixContext, diag barrelman.Diagnostic) ([]codemod.Patch, error) {
	schemas := componentsSchemasMapping(ctx)
	if schemas == nil {
		return nil, nil
	}
	if codemod.MappingHasKey(schemas, ctx.Source, "ProblemDetails") {
		return nil, nil
	}
	indent := codemod.ChildIndent(schemas, ctx.Source)
	// problemDetailsSchemaBody begins with `ProblemDetails:` at column 0
	// and a 2-space base indent. We re-indent every non-empty line to
	// the schemas-child indent so it sits correctly.
	body := codemod.IndentFragment(problemDetailsSchemaBody, indent)
	// Strip the "ProblemDetails:" key from the body so we can pass the
	// remaining value through InsertMappingPair.
	firstNL := bytes.IndexByte([]byte(body), '\n')
	if firstNL < 0 {
		return nil, nil
	}
	value := body[firstNL:] // includes leading newline
	insertAt := endOfMappingContentExported(schemas, ctx.Source)
	pad := bytes.Repeat([]byte(" "), indent)
	fragment := fmt.Sprintf("\n%sProblemDetails:%s", pad, value)
	patch := codemod.Patch{
		URI:         ctx.URI,
		StartByte:   uint(insertAt),
		EndByte:     uint(insertAt),
		Replacement: []byte(fragment),
		Description: "insert shared ProblemDetails schema under components.schemas",
		RuleID:      diag.Code,
	}
	return []codemod.Patch{patch}, nil
}

// ErrorCorrelationID implements the Fix for
// sailpoint-error-correlation-id: adds a correlationId property to the
// existing ProblemDetails schema when missing. Requires
// components.schemas.ProblemDetails to already exist; the
// shared-component fix handles the bootstrap.
func ErrorCorrelationID(ctx *codemod.FixContext, diag barrelman.Diagnostic) ([]codemod.Patch, error) {
	problemDetails := problemDetailsSchemaNode(ctx)
	if problemDetails == nil {
		return nil, nil
	}
	propertiesVal := codemod.MappingValueNode(problemDetails, ctx.Source, "properties")
	if propertiesVal == nil {
		return nil, nil
	}
	properties := codemod.EnclosingBlockMapping(propertiesVal)
	if properties == nil || codemod.MappingHasKey(properties, ctx.Source, "correlationId") {
		return nil, nil
	}
	childIndent := codemod.ChildIndent(properties, ctx.Source)
	inner := childIndent + 2
	pad := bytes.Repeat([]byte(" "), inner)
	value := fmt.Sprintf("\n%stype: string\n%sformat: uuid\n%sdescription: Unique identifier correlating this response to a server-side trace.",
		pad, pad, pad)
	patch := codemod.InsertMappingPair(properties, ctx.Source, "correlationId", value)
	patch.URI = ctx.URI
	patch.RuleID = diag.Code
	patch.Description = "insert correlationId property on ProblemDetails"
	return []codemod.Patch{patch}, nil
}

// componentsSchemasMapping walks from the document root to
// components.schemas. Returns nil when the document has no
// components: or components.schemas: keys (the caller then cannot
// fix the issue without a much larger rewrite).
func componentsSchemasMapping(ctx *codemod.FixContext) *ts.Node {
	root := rootMapping(ctx)
	if root == nil {
		return nil
	}
	componentsVal := codemod.MappingValueNode(root, ctx.Source, "components")
	if componentsVal == nil {
		return nil
	}
	components := codemod.EnclosingBlockMapping(componentsVal)
	if components == nil {
		return nil
	}
	schemasVal := codemod.MappingValueNode(components, ctx.Source, "schemas")
	if schemasVal == nil {
		return nil
	}
	return codemod.EnclosingBlockMapping(schemasVal)
}

// problemDetailsSchemaNode returns the ProblemDetails schema's
// block_mapping (the value side of components.schemas.ProblemDetails),
// or nil when the schema is missing.
func problemDetailsSchemaNode(ctx *codemod.FixContext) *ts.Node {
	schemas := componentsSchemasMapping(ctx)
	if schemas == nil {
		return nil
	}
	val := codemod.MappingValueNode(schemas, ctx.Source, "ProblemDetails")
	if val == nil {
		return nil
	}
	return codemod.EnclosingBlockMapping(val)
}

// rootMapping returns the top-level block_mapping of the document:
// usually the object containing openapi/info/paths. Returns nil for
// non-object root documents.
func rootMapping(ctx *codemod.FixContext) *ts.Node {
	if ctx == nil || ctx.Index == nil {
		return nil
	}
	tree := ctx.Index.Tree()
	if tree == nil {
		return nil
	}
	root := tree.RootNode()
	if root == nil {
		return nil
	}
	return codemod.EnclosingBlockMapping(root)
}

// endOfMappingContentExported mirrors codemod.endOfMappingContent for
// callers that need the value directly. Published here under a Fixes
// name so we can reuse it in this package without exporting the
// internal helper from codemod.
func endOfMappingContentExported(parent *ts.Node, src []byte) int {
	if parent == nil {
		return 0
	}
	end := int(parent.EndByte())
	for end > int(parent.StartByte()) {
		c := src[end-1]
		if c == '\n' || c == ' ' || c == '\t' || c == '\r' {
			end--
			continue
		}
		break
	}
	return end
}
